### ISSUE TITLE
Writing error

### ISSUE THREAD

**Issue by alphonse-lin** [talanc/SketchUpSharp#1]
Thank you for this talented project, I tried to run the writing project, but I got this error. Do you have any idea about what kind of dependencies I have missed? I already out SketchUpAPI.dll and SketchUpCommonPreferences.dll into the "SketchUpSharp" folder.

![image](https://user-images.githubusercontent.com/38575020/168579184-d389e7d5-8391-44f1-a710-fc5471e6634f.png)

![image](https://user-images.githubusercontent.com/38575020/168579580-d3ce58ba-a1f3-4851-aaa7-db0a48fad59e.png)

**Comment by talanc** [comment]
The DLLs should be in your bin folder. You shouldn't need to do that though. Extract the SDK and it all should just build and run without issues.

1) Extract the SDK zip to a folder named sdk.
(SDK zip can be found in the downloads folder)

2) After extraction, the folder structure should look like:
- downloads
- generation
- sdk <-- contents of the SDK here
- sources

**Comment by talanc** [comment]
Also I'll create a getting started guide in the next week or so.

**Comment by talanc** [comment]
And done.
